# Generated by Django 3.1.5 on 2021-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(choices=[('Single-Room', 'Single-Room'), ('Double-Room', 'Double-Room'), ('Family-Room', 'Family-Room')], default='None', max_length=15)),
                ('room_image', models.ImageField(upload_to='media/rooms_images')),
                ('room_description', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=100)),
                ('room_ratings', models.IntegerField(default=1)),
                ('room_price_per_night', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
