# Generated by Django 3.1.5 on 2021-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominformation',
            options={'verbose_name_plural': 'RoomInformation'},
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_image',
            field=models.ImageField(blank=True, upload_to='media/rooms_images'),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_name',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
