# Generated by Django 3.1.5 on 2021-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210312_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominformation',
            name='room_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_price_per_night',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
