# Generated by Django 3.1.5 on 2021-03-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210312_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominformation',
            name='room_price_per_night',
            field=models.FloatField(),
        ),
    ]
