# Generated by Django 3.1.5 on 2021-03-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20210312_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominformation',
            name='room_price_per_night',
        ),
    ]
