# Generated by Django 3.1.5 on 2021-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_roominformation_room_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominformation',
            name='room_price_per_night',
            field=models.FloatField(default=46.0),
            preserve_default=False,
        ),
    ]
