# Generated by Django 3.1.5 on 2021-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_roominformation_room_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominformation',
            name='room_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_image',
            field=models.ImageField(upload_to='media/rooms_images'),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_name',
            field=models.CharField(choices=[('Single-Room', 'Single-Room'), ('Double-Room', 'Double-Room'), ('Family-Room', 'Family-Room')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
    ]
